INSERT INTO categorias (titulo, descricao, url_imagem) VALUES
    ('Grandes Cidades', 'Os grandes centros urbanos abrigam empresas e serviços de alto padrão e sofisticação, grande variedade e diversidade de restaurantes, passeios e compras.', 'https://t2-grupo8.s3.amazonaws.com/categorias/sp.jpg'),
    ('Praias', 'Destinos litorâneos que possibilitam a realizações de atividades balneares como surf, stand up paddle e mergulho.', 'https://t2-grupo8.s3.amazonaws.com/categorias/maragogi.jpeg'),
    ('História e Cultura','Cidades brasileiras construídas durante o período colonial que ainda mantêm grande parte do seu casario conservado', 'https://t2-grupo8.s3.amazonaws.com/categorias/salvador.jpg'),
    ('Ecoturismo','Destinos de natureza com foco em sustentabilidade.', 'https://t2-grupo8.s3.amazonaws.com/categorias/chapada-diamantina.jpg');

INSERT INTO caracteristicas (nome, icone) VALUES
    ('Aceita Pets', 'pets'),
    ('Televisor', 'tv'),
    ('Ar Condicionado', 'ac_unit'),
    ('Café da Manhã', 'free_breakfast'),
    ('Piscina', 'pool'),
    ('Wi-Fi', 'wifi'),
    ('Estacionamento', 'directions_car'),
    ('Academia', 'fitness_center'),
    ('Mobilidade Reduzida', 'accessible'),
    ('Quarto Não Fumante', 'smoke_free');

INSERT INTO cidades (nome, uf, pais) VALUES
    ('Fortaleza', 'CE', 'Brasil'),
    ('Maceió', 'AL', 'Brasil'),
    ('Florianópolis', 'SC', 'Brasil'),
    ('Natal', 'RN', 'Brasil'),
    ('São Paulo', 'SP', 'Brasil'),
    ('Rio de Janeiro', 'RJ', 'Brasil'),
    ('Belo Horizonte', 'MG', 'Brasil'),
    ('Curitiba', 'PR', 'Brasil'),
    ('Salvador', 'BA', 'Brasil'),
    ('Olinda', 'PE', 'Brasil'),
    ('Petrópolis', 'RJ', 'Brasil'),
    ('Ouro Preto', 'MG', 'Brasil'),
    ('Alto Paraíso de Goiás', 'GO', 'Brasil'),
    ('Lençois','BA', 'Brasil'),
    ('Bonito', 'MS', 'Brasil'),
    ('Mateiros', 'TO', 'Brasil');

INSERT INTO funcoes (nome) VALUES
    ('ROLE_CLIENT'),
    ('ROLE_ADMIN'),
    ('ROLE_PROPRIETOR');

INSERT INTO usuarios (nome, sobrenome, email, senha,  ativado, id_funcao, usuario_tipo) VALUES
    ('Thays', 'Gama', 'thays@gama.com', '$2a$10$P/tNdWZgyOMThfSx.YCxke7K7FG3cAfKQD4QVmJb.wXWASgja2bSe', 1, 1, 'C'),
    ('Esther', 'Maria', 'esther@maria.com', '$2a$10$I/e4FGU5pV1gbkbA8WPUFeGnnLYJJuX9kfb/ildzTqutPrZZ6NYOq',1, 2, 'A'),
    ('Leonardo', 'Martins', 'leo@martins.com', '$2a$10$4q439DiaETwZsjW.UsPRbu5kJtejJYF1hPMu8do1wvleqnM4/9AlK',1, 3, 'P');

INSERT INTO produtos (nome, descricao,endereco, latitude, longitude, regras_gerais, regras_seguranca, regras_cancelamento, id_cidade, id_categoria, id_proprietario) VALUES
    ('Beach Beira Mar','Além de ser bem localizado para viagens de negócio ou lazer, o nosso apartamento oferece uma experiência autêntica à sua estadia, com uma vista linda da praia, conforto e está rodeado de restaurantes e todo o tipo de serviços. Faça a sua reserva. Tenha férias inesquecíveis no Beach Beira Mar, apenas a 10 metros da praia. Espaço espaçoso e confortável para casais, solteiros e amigos. Todo climatizado e com wi-fi grátis, é perfeito para conhecer a cidade, pela sua localização privilegiada, seja a trabalho ou lazer.','Rua do amor, 1995','-3.71852584954214','-38.520076257714315','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>',1,2,3),
    ('Casa de Ondina', 'Casa de Ondina foi pensada para receber meus hóspedes da forma mais carinhosa e aconchegante possível. Com móveis planejados novos e modernos, cozinha completa com utensílios, um quarto com cama Queen Size bem confortável e ar condicionado, smartv, wi fi alta velocidade e cortinas com blackout, edifício novo e moderno lcalizado no coração da Ponta Verde. Uma maneira inteligente e acessível de se hospedar e curtir as belezas da capital alagoana.','Rua da alegria, 22','-9.647142034214454', '-35.69673839767153','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 2, 2, 3),
    ('Lexus Residence Apto 304', 'Aproveite a infraestrutura nova e moderna deste lindo apartamento completo localizado a 260 metros do mar, em um dos bairros mais sofisticados de Florianópolis: Jurerê.Perfeito para você e sua família. A apenas 100 metros de farmácias, mercados, restaurantes, bares e cafés. Aproveite está ótima oportunidade e venha se hospedar conosco em Jurerê.','Av das ostras, 888', '-27.59659577186178', '-48.55268202589793','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 3,2,3),
    ('Prime Flat Ponta Negra', 'Estamos tomando todos os cuidados de higienização frente ao COVID19 - Flat de alto padrão que localizado no coração de Ponta Negra, uma das mais badaladas praias do nordeste. A 300 metros da praia, próximo de excelentes restaurantes e bistrôs e a 600 metros dos mais interessantes bares e casas noturnas, o flat fora carinhosamente montado e decorado para seu deleite, contando com Wi-Fi gratuito, duas Tvs Smart com Netflix, cama queen, barra de banho com jato de massagem','Rua Dr. Aloísio, 45', '-5.877786118711293', '-35.1384764651081','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 4,2, 3),
    ('Home Bela Vista APM1303', 'Você se sentirá ótimo neste Studio. A localização é privilegiada e torna o acesso a qualquer ponto da cidade simples e rápido. Próximo à Av Brig. Luís Antônio, Av. 23 de Maio, Metrô e todos os pontos turísticos, restaurantes, cafés e bares do Centro renovado. O conforto é garantido com cozinha equipada, varanda, Wi-Fi e ar-condicionado. Muito bem decorado com tudo novinho em um edifício moderno e seguro com piscina e academia.','Rua Maria da Silva, 195', '-23.561248933203643', '-46.65598374197827','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 5,1, 3),
    ('Moderno Studio', 'Este moderno e recém-reformado Studio tem vista para o Cristo Redentor e uma localização impecável. A 230 metros da estação de Metrô Siqueira Campos, você poderá visitar os principais pontos turísticos da Zona Sul do Rio com praticidade, além de estar a apenas 10 minutos da Praia de Copacabana. Dentro da acomodação, você vai encontrar Smart TV, internet de 250mbps e uma workstation, além dos demais itens fundamentais para tornar sua estadia aconchegante e única.','Rua do encanto, 543','-22.984667581746898', '-43.209020383064384','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 6,1, 3),
    ('Alto Padrão no coração da Savassi', 'Apartamento muito bem equipado e confortável, fica num prédio completo que possui, piscina externa e interna, jacuzzi, academia, sauna, área gourmet, co-working e estacionamento, além de estar localizado no coração da Savassi, perto de vários restaurante e barzinhos super agradáveis e próximo do Shopping Pátio Savassi, e na proximidade também temos supermercados e farmácias.','Rua João Vicente, 22', '-19.934869707884936','-43.92943621209394','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 7,1,3),
    ('Apto 1Q - 300MB Fibra Ótica', 'Meu espaço é perto do: Shopping Estação, Bancos, Panificadora 24h, Postos de Gasolina, Faculdades, Pontos de Transporte Público e Táxi. Você vai amar meu espaço, é ótimo para descanso e lazer, até mesmo para você que está vindo a negócios. Apartamento mobiliado e preparado nos mínimos detalhes para proporcionar uma estadia confortável e despreocupada. Bom para casais, aventuras individuais, viajantes a negócios, famílias com crianças e amigos peludos.','Rua Dragão do Mar, 369', '-25.441411827641918','-49.238034752535086','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 8,1,3),
    ('LOFT em Big House Barris', 'Localizado no Coração de Salvador Big House Barris um casarão projetado para as Grandes Famílias dos séculos passados , tem sua característica de preservar a sensação de " está em casa". Atualmente administrada pelos Gotelips family Big House Barris tem sua própria história traços do que foi uma residência , república estudantil e atualmente hospedagem na modalidade guest House ou casas de aluguel, com 12 suítes e atualmente convertidas em apartamentos apartamento 1/4, loft e Jk','Rua Tiradentes, 187', '-13.007529633582655', '-38.49008277777353','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 9,3,3),
    ('Casa Fruta pão', 'No coração do sitio historico de Olinda, cidade inscrita no patrimônio mundial da humanidade. Uma base ideal para descobrir a cidade e a região. Todo charme de uma casa de estilo colonial, ampla, ventilada, grande quintal arborizado, pé de fruta-pão centenário, mangueira, coqueiros, terraço, redes.. A dois passos à pé dos atrativos turisticos e comodidades: museus, igrejas, ponto de taxi, ônibus, bares e restaurantes típicos.','Rua Luiza Rosa, 231', '-8.013604025137488', '-34.84982710022799','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 10,3,3),
    ('Apê Petrô', 'O Apê Petrô fica localizado no coração do centro histórico de Petrópolis e é possível visitar todo o centro a pé. Os melhores restaurantes, cervejarias, pontos turísticos e serviços a poucos minutos de caminhada. O Apartamento é arejado, de fundos e com vista privativa. Conta com confortáveis 3 quartos, elevadores, portaria (24h), Wifi, segurança e higiene para você poder explorar o que há de melhor na Cidade Imperial.','Rua Dr. Mauricio Canela, 2295', '-22.506346287236585', '-43.16562645603897','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 11,3,3),
    ('Varanda do Inconfidente', 'Estamos com espaço maior entre hospedes para melhor limpeza da casa e hospedagens reduzidas. A Varanda do Inconfidente fica menos de 10 minutos a pé do bairro Rosário. Pelo caminho, supermercado, padaria, sacolão e também a belíssima igreja do Rosário. A casa super confortável que vivemos a nossa infância está disponível para receber você! Casa ampla, clara com área de churrasco, varanda e lareira. Venha conhecer Ouro Preto e fique em nossa casa!','Av. Treze de Maio, 695', '-20.388798825916385', '-43.49561204910051','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 12,3,3),
    ('Casa Gaia - Conforto e Sossego', 'Casa aconchegante com quarto e sala amplos. Deck de madeira suspenso com rede criam um espaço super agradável. As grandes portas e janelas de vidro permitem que a luz entre, deixando a casa iluminada e ventilada. Localização privilegiada próxima ao centro. Bairro tranquilo com ruas de terra e cercado pela natureza. *Para pets há taxa adicional e é preciso selecionar essa opção caso venha com seu pet.','Rua Carla Joaquina, 44', '-14.134552298678177', '-47.50806416732771','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 13,4,3),
    ('Chalé Amarelo | Eco Vila Lençóis', 'Chalé superior na Eco-Vila, com 1 quarto e sofá-cama na sala. Tudo novinho e cheio de charme. O chalé fica no primeiro andar com vista e contato com a natureza. Ele foi inteira pensado no conforto para que você, a sua família e amigos possam desfrutar de todo conforto e contato com a natureza! Os hóspedes desfrutarão de todo o espaço com autonomia.','Rua dos republicanos, 336', '-12.563185970778346', '-41.38684331994933','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>',  14,4,3),
    ('Casa no Coração de Bonito', 'Uma casa aconchegante que respira arte regional, no coração de Bonito, localizada a poucos passos da Av. Pilad Rebuá, a principal da cidade. A casa dispõe de ampla sala de estar, internet wifi, copa conjugada a cozinha, dispomos de geladeira, fogão, mesa, cadeiras, armário e utensílios básicos de cozinha. Os dois quartos possuem ar condicionado, sendo um deles suíte, disponibilizamos jogo de cama e banho completos. Banheiro mais simples na área externa. Estamos à disposição para atende- los.','Rua da amizade, 897','-21.12821961096471', '-56.48204227331589','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 15,4,3),
    ('Casa Centro de Mateiros ', 'Casa nova de alto padrão, com quintal, espaço multifuncional para homeofice e práticas corporais. Completamente equipada e limpa para o conforto de grupos e famílias. Nosso melhor público é o que dispõe de mais tempo para captar melhor a região, principalmente voltados ao turismo de experiências, de propósitosde e de bases comunitárias. Apreciamos hospedar grupos de artistas, biólogos, terapeutas e quaisquer estudantes/profissionais que lidam com Natureza e Desenvolvimento Humano.', 'Rua dos sabiás, 761', '-10.545095814781076', '-46.41482964914891','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 16,4,3),
    ('Iracema Residencial', 'Prédio aconchegante, moderno, silencioso e perto do centro cultural Dragão do Mar, da praia de Iracema e da boemia alencarina! De lá você visita todas as praias do Ceará, de Jeriquaquara à Canoa Quebrada com serviço de translado em que lhe buscam no próprio prédio. Esse é o diferencial desse prédio.','Rua Zumbi dos Palmares, 761','-3.71852584954214', '-38.520076257714315','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 1,2,3),
    ('Aconchego no coração da Ponta Verde','Sabendo que a experiência e oportunidade de uma viagem é algo que precisa ficar para sempre em nossas memórias nós preparamos nosso apartamento pensando em cada detalhe para que tudo seja perfeito para você, nosso querido hóspede. Nosso Apartamento é inteligente! Enxoval todo novo de quarto, sala e cozinha…vocês ficarão encantados!','Rua do quilombo, 1111','-9.647142034214454', '-35.69673839767153','<ul><li>Check-out: 10:00</li><li>Não é permitido festas</li><li>Não fumar</li></ul>','<ul><li>Diretrizes de distanciamento social e outras regulamentações relacionadas ao coronavírus se aplicam</li><li>Detector de fumaça</li><li>Depósito de segurança</li></ul>','<p>Adicione as datas da viagem para obter detalhes de cancelamento para esta estadia</p>', 2,2,3);

INSERT INTO imagens (titulo, url, id_produto) VALUES
    ('Sala 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-01.jpg', 1),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-02.jpg', 1),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-03.jpg', 1),
    ('Sala 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-04.jpg', 1),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-05.jpg', 1),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-06.jpg', 1),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-01.jpg', 2),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-02.jpg', 2),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-03.jpg', 2),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-04.jpg', 2),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-05.jpg', 2),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-06.jpg', 2),
    ('WC 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-07.jpg', 2),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-01.jpg', 3),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-02.jpg', 3),
    ('Sala Estar 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-03.jpg', 3),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-04.jpg', 3),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-05.jpg', 3),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-01.jpg', 4),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-02.jpg', 4),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-03.jpg', 4),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-04.jpg', 4),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-05.jpg', 4),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-01.jpg', 5),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-02.jpg', 5),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-03.jpg', 5),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-04.jpg', 5),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-05.jpg', 5),
    ('Escritório 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-01.jpg', 6),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-02.jpg', 6),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-03.jpg', 6),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-04.jpg', 6),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-05.jpg', 6),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-01.jpg', 7),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-02.jpg', 7),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-03.jpg', 7),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-04.jpg', 7),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-05.jpg', 7),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-01.jpg', 8),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-02.jpg', 8),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-03.jpg', 8),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-04.jpg', 8),
    ('WC 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-05.jpg', 8),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-01.jpg', 9),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-02.jpg', 9),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-03.jpg', 9),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-04.jpg', 9),
    ('Sala Estar 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-05.jpg', 9),
    ('Sala Estar 4', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-06.jpg', 9),
    ('Sala 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-01.jpg', 10),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-02.jpg', 10),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-03.jpg', 10),
    ('Sala 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-04.jpg', 10),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-05.jpg', 10),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/01/ap01-06.jpg', 10),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-01.jpg', 11),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-02.jpg', 11),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-03.jpg', 11),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-04.jpg', 11),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-05.jpg', 11),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-06.jpg', 11),
    ('WC 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/02/ap02-07.jpg', 11),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-01.jpg', 12),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-02.jpg', 12),
    ('Sala Estar 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-03.jpg', 12),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-04.jpg', 12),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/03/ap03-05.jpg', 12),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-01.jpg', 13),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-02.jpg', 13),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-03.jpg', 13),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-04.jpg', 13),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/04/ap04-05.jpg', 13),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-01.jpg', 14),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-02.jpg', 14),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-03.jpg', 14),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-04.jpg', 14),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/05/ap05-05.jpg', 14),
    ('Escritório 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-01.jpg', 15),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-02.jpg', 15),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-03.jpg', 15),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-04.jpg', 15),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/06/ap06-05.jpg', 15),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-01.jpg', 16),
    ('Sala Jantar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-02.jpg', 16),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-03.jpg', 16),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-04.jpg', 16),
    ('Quarto 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/07/ap07-05.jpg', 16),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-01.jpg', 17),
    ('WC 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-02.jpg', 17),
    ('Cozinha 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-03.jpg', 17),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-04.jpg', 17),
    ('WC 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/08/ap08-05.jpg', 17),
    ('Quarto 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-01.jpg', 18),
    ('Quarto 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-02.jpg', 18),
    ('Sala Estar 1', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-03.jpg', 18),
    ('Sala Estar 2', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-04.jpg', 18),
    ('Sala Estar 3', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-05.jpg', 18),
    ('Sala Estar 4', 'https://t2-grupo8.s3.amazonaws.com/produtos/09/ap09-06.jpg', 18);

INSERT INTO produtos_caracteristicas (id_produto, id_caracteristica) VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 6),
    (2, 6),
    (2, 2),
    (2, 5),
    (3, 6),
    (3, 3),
    (3, 7),
    (4, 6),
    (4, 3),
    (4, 5),
    (5, 6),
    (5, 2),
    (5, 4),
    (5, 7),
    (6, 6),
    (6, 4),
    (6, 3),
    (6, 8),
    (7, 6),
    (7, 2),
    (7, 5),
    (8, 6),
    (8, 3),
    (8, 7),
    (8, 9),
    (9, 6),
    (9, 4),
    (9, 5),
    (9, 10),
    (10, 6),
    (10, 3),
    (10, 7),
    (10, 9),
    (11, 6),
    (11, 4),
    (11, 5),
    (12, 6),
    (12, 3),
    (12, 9),
    (12, 10),
    (13, 6),
    (13, 5),
    (13, 7),
    (13, 8),
    (14, 6),
    (14, 3),
    (14, 8),
    (15, 6),
    (15, 2),
    (15, 10),
    (16, 6),
    (16, 3),
    (16, 9),
    (17, 6),
    (17, 7),
    (17, 10),
    (18, 2),
    (18, 6);


INSERT INTO reservas (hora_reserva, data_entrada, data_saida, id_cliente, id_produto) VALUES
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 1),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 2),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 3),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 4),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 5),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 6),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 7),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 8),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 9),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 10),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 11),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 12),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 13),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 14),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 15),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 16),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 17),
    (CURRENT_TIME , '2022-04-07', '2022-04-10', 1, 18);

INSERT INTO avaliacoes (id_usuario, id_produto, score) VALUES
    (1, 1, 5),
    (1, 2, 4),
    (1, 3, 5),
    (1, 5, 3),
    (1, 6, 5),
    (1, 8, 2),
    (1, 9, 5),
    (1, 10, 4),
    (1, 12, 4),
    (1, 13, 5),
    (1, 15, 3),
    (1, 16, 3),
    (1, 17, 5);

INSERT INTO produtos_favoritos (id_usuario, id_produto) VALUES
    (1, 1),
    (1, 3),
    (1, 6),
    (1, 9),
    (1, 13),
    (1, 17);